name: pandas-skills

dependencies:
  - python=3.9.2
  - numpy=1.20.2
  - scipy=1.6.2
  - spacy=3.0.5
  - pandas=1.2.3
  - matplotlib=3.4.1
  - ipython=7.22.0
  - ipykernel=5.5.3
  - notebook=6.3.0
  - jupyterlab=3.0.12
  - pip=20.0*

  - pip:
    - pylint>=2.7